/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import dbconnector.dbconnect;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Ariunbuyan
 */
public class AguulahDesc extends javax.swing.JFrame {

    dbconnect db = new dbconnect();
    Dashboard d = new Dashboard();
    Connection con;
    ResultSet urdun;
    int xMouse, yMouse;

    String bname, btoo, bprice, birsen_date, bduusah_date, cid;
    String name, too, price, bid, setIdate, setDdate;
    int baraa_id;

    /**
     * Creates new form AguulahDesc
     */
    public AguulahDesc(String get_baraa_id) {
        initComponents();
        ComboCatName();
        this.setLocation(250, 150);

        viewBid.setText("Барааны ID: " + get_baraa_id);
        try {
            urdun = db.login("SELECT a.id, a.name, a.too, a.price, a.cid, a.irsen_date, a.duusah_date "
                    + "FROM aguulah a, categories c WHERE a.cid = c.id and a.id = " + get_baraa_id);
            if (urdun.next()) {
                bname = urdun.getString("name");
                btoo = urdun.getString("too");
                bprice = urdun.getString("price");
                cid = urdun.getString("cid");
                birsen_date = urdun.getString("irsen_date");
                bduusah_date = urdun.getString("duusah_date");

                viewBname.setText(bname);
                viewBtoo.setText(btoo);
                viewBprice.setText(bprice);

                try {
                    Date irsenDate = new SimpleDateFormat("yyyy-MM-dd").parse(birsen_date);
                    Date duusahDate = new SimpleDateFormat("yyyy-MM-dd").parse(bduusah_date);
                    viewIrsenDate.setDate(irsenDate);
                    viewDuusahDate.setDate(duusahDate);
                } catch (ParseException ex) {
                    Logger.getLogger(AguulahDesc.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

            urdun = db.login("select name from categories where id = " + cid);
            if (urdun.next()) {
                viewBcat.setSelectedItem(urdun.getString("name"));
            }
            baraa_id = Integer.parseInt(get_baraa_id);
        } catch (SQLException ex) {
            Logger.getLogger(AguulahDesc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void ComboCatName() {
        try {
            urdun = db.login("select name from categories order by id desc");
            while (urdun.next()) {
                viewBcat.addItem(urdun.getString("name"));
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        viewBid = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        viewBname = new javax.swing.JTextField();
        viewBtoo = new javax.swing.JTextField();
        viewBprice = new javax.swing.JTextField();
        viewBcat = new javax.swing.JComboBox<>();
        viewIrsenDate = new com.toedter.calendar.JDateChooser();
        viewDuusahDate = new com.toedter.calendar.JDateChooser();
        aguulah_baraa_zasah = new javax.swing.JButton();
        aguulah_baraa_ustgah = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(320, 380));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toolbar.setBackground(new java.awt.Color(153, 153, 153));
        toolbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                toolbarMouseDragged(evt);
            }
        });
        toolbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                toolbarMousePressed(evt);
            }
        });
        toolbar.setLayout(new java.awt.BorderLayout());
        getContentPane().add(toolbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 30));

        bg.setBackground(new java.awt.Color(0, 51, 204));
        bg.setPreferredSize(new java.awt.Dimension(614, 350));

        viewBid.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        viewBid.setForeground(new java.awt.Color(255, 255, 255));
        viewBid.setText("ID");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Нэр :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Тоо :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Үнэ :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Категори:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ирсэн");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Дуусах");

        viewIrsenDate.setDateFormatString("yyyy-MM-dd");

        viewDuusahDate.setDateFormatString("yyyy-MM-dd");

        aguulah_baraa_zasah.setText("Засах");
        aguulah_baraa_zasah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aguulah_baraa_zasahActionPerformed(evt);
            }
        });

        aguulah_baraa_ustgah.setText("Устгах");

        backBtn.setText("Буцах");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addComponent(jLabel1)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))))
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewBtoo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viewBname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viewBprice, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(viewBcat, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewIrsenDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viewDuusahDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(viewBid, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(backBtn)
                        .addGap(36, 36, 36)
                        .addComponent(aguulah_baraa_ustgah)
                        .addGap(32, 32, 32)
                        .addComponent(aguulah_baraa_zasah)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(viewBid)
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(viewBname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(viewBtoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(viewBprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(viewBcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewIrsenDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewDuusahDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(aguulah_baraa_ustgah)
                    .addComponent(aguulah_baraa_zasah))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 320, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        setVisible(false);
        d.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void aguulah_baraa_zasahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aguulah_baraa_zasahActionPerformed
        name = viewBname.getText().toString();
        too = viewBtoo.getText().toString();
        price = viewBprice.getText().toString();

        setIdate = ((JTextField) viewIrsenDate.getDateEditor().getUiComponent()).getText();
        setDdate = ((JTextField) viewDuusahDate.getDateEditor().getUiComponent()).getText();

        try {
            bid = viewBcat.getSelectedItem().toString();
            urdun = db.login("select id from categories where name = '" + bid + "'");
            if (urdun.next()) {
                cid = urdun.getString("id");
            }

            urdun = db.login("select name from aguulah where name = '" + name + "'");
            if (urdun.next()) {
                JOptionPane.showMessageDialog(null, urdun.getString("name") + " бараа байна.");
            } else {
                db.exec("UPDATE aguulah SET name = '" + name + "', "
                        + "too = '" + too + "', "
                        + "price = '" + price + "', "
                        + "cid = '" + cid + "', "
                        + "irsen_date = '" + setIdate + "', "
                        + "duusah_date = '" + setDdate + "' WHERE id = " + baraa_id);
                setVisible(false);
                d.Tbl_Aguulah_Hewleh();
                d.Tbl_Stock_Share();
                d.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AguulahDesc.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_aguulah_baraa_zasahActionPerformed

    private void toolbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolbarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_toolbarMouseDragged

    private void toolbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolbarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_toolbarMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aguulah_baraa_ustgah;
    private javax.swing.JButton aguulah_baraa_zasah;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel toolbar;
    private javax.swing.JComboBox<String> viewBcat;
    private javax.swing.JLabel viewBid;
    private javax.swing.JTextField viewBname;
    private javax.swing.JTextField viewBprice;
    private javax.swing.JTextField viewBtoo;
    private com.toedter.calendar.JDateChooser viewDuusahDate;
    private com.toedter.calendar.JDateChooser viewIrsenDate;
    // End of variables declaration//GEN-END:variables
}
