/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import dbconnector.dbconnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ariunbuyan
 */
public class BaraaHuwiarlah extends javax.swing.JFrame {

    dbconnect db = new dbconnect();
    Dashboard d = new Dashboard();
    ResultSet urdun, shop;
    int xMouse, yMouse;

    String getCName, getName, getToo, getPrice;
    int btoo, baraa_id, sid, hariu, num;

    /**
     * Creates new form BaraaHuwiarlah
     */
    public BaraaHuwiarlah(String get_baraa_id) {
        initComponents();
        this.setLocation(250, 150);
        Combo_Shops();

        urdun = db.login("SELECT name, too, price, cid FROM aguulah WHERE id = " + get_baraa_id);
        try {
            if (urdun.next()) {
                getCName = urdun.getString("cid");

                viewBname.setText("Барааны нэр: " + urdun.getString("name"));
                viewBtoo.setText("Барааны тоо: " + urdun.getString("too"));
                viewBprice.setText("Барааны үнэ: " + urdun.getString("price"));

                baraa_id = Integer.parseInt(get_baraa_id);

                urdun = db.login("select name from categories where id = " + getCName);
                if (urdun.next()) {
                    combo_shops.setSelectedItem(urdun.getString("name"));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(BaraaHuwiarlah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void Combo_Shops() {
        urdun = db.login("select sname from shops");
        try {
            while (urdun.next()) {
                combo_shops.addItem(urdun.getString("sname"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(BaraaHuwiarlah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        toolbar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        viewBname = new javax.swing.JLabel();
        viewBtoo = new javax.swing.JLabel();
        viewBprice = new javax.swing.JLabel();
        get_baraa_too = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        combo_shops = new javax.swing.JComboBox<>();
        stock_shareBtn = new javax.swing.JButton();
        stock_backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(430, 350));
        getContentPane().setLayout(null);

        toolbar.setBackground(new java.awt.Color(102, 102, 102));
        toolbar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        toolbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                toolbarMouseDragged(evt);
            }
        });
        toolbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                toolbarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout toolbarLayout = new javax.swing.GroupLayout(toolbar);
        toolbar.setLayout(toolbarLayout);
        toolbarLayout.setHorizontalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        toolbarLayout.setVerticalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Бараа хувиарлах хэсэг");

        viewBname.setText("Нэр");

        viewBtoo.setText("Тоо");

        viewBprice.setText("Үнэ");

        jLabel5.setText("Тухайн дэлгүүрт өгөх барааны тоо:");

        combo_shops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_shopsActionPerformed(evt);
            }
        });

        stock_shareBtn.setText("Хувиарлах");
        stock_shareBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stock_shareBtnActionPerformed(evt);
            }
        });

        stock_backBtn.setText("Буцах");
        stock_backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stock_backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(get_baraa_too)
                            .addComponent(combo_shops, 0, 280, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stock_shareBtn)
                            .addComponent(stock_backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(viewBname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(viewBtoo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(viewBprice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(viewBname)
                .addGap(18, 18, 18)
                .addComponent(viewBtoo)
                .addGap(18, 18, 18)
                .addComponent(viewBprice)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(get_baraa_too, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stock_shareBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_shops, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stock_backBtn))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 420, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stock_backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stock_backBtnActionPerformed
        setVisible(false);
        d.tabbedPane.setSelectedIndex(2);
        d.setVisible(true);
    }//GEN-LAST:event_stock_backBtnActionPerformed

    private void stock_shareBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stock_shareBtnActionPerformed
        btoo = Integer.parseInt(get_baraa_too.getText());

        try {
            urdun = db.login("select too from aguulah where id = " + baraa_id);

            if (urdun.next()) {
                num = urdun.getInt("too");
                if (btoo <= num) {
                    hariu = num - btoo;

                    shop = db.login("select id from shops where sname = '" + combo_shops.getSelectedItem().toString() + "'");
                    if (shop.next()) {
                        sid = shop.getInt("id");
                        db.exec("insert into baraa (sid, aid, btoo) values ('" + sid + "', '" + baraa_id + "', " + btoo + ")");
                        db.exec("update aguulah set too = " + hariu + " where id = " + baraa_id);
                        JOptionPane.showMessageDialog(null, "Амжилттай хувиарлагдлаа.");
                        setVisible(false);
                        d.Tbl_Shop_huwiarilsan_baraa();
                        d.Tbl_Aguulah_Hewleh();
                        d.Tbl_Shop_huwiarilsan_baraa();
                        d.tabbedPane.setSelectedIndex(2);
                        d.setVisible(true);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Барааны тоо хэт их байна эсвэл бараа дууссан байна.");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(BaraaHuwiarlah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_stock_shareBtnActionPerformed

    private void combo_shopsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_shopsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_shopsActionPerformed

    private void toolbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolbarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_toolbarMouseDragged

    private void toolbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolbarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_toolbarMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_shops;
    private javax.swing.JTextField get_baraa_too;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton stock_backBtn;
    private javax.swing.JButton stock_shareBtn;
    private javax.swing.JPanel toolbar;
    private javax.swing.JLabel viewBname;
    private javax.swing.JLabel viewBprice;
    private javax.swing.JLabel viewBtoo;
    // End of variables declaration//GEN-END:variables
}
