/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import dbconnector.dbconnect;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ariunbuyan
 */
public class CategoryAction extends javax.swing.JFrame {

    private dbconnect db = new dbconnect();
    private Dashboard d = new Dashboard();
    private ResultSet urdun;
    private String getCatName;
    private int xMouse, yMouse, cat_id;

    /**
     * Creates new form CategoryAction
     */
    public CategoryAction(String get_cat_id) {
        initComponents();
        this.setLocation(300, 200);

        try {
            urdun = db.login("select name from categories where id = " + get_cat_id);
            if (urdun.next()) {
                stockName.setText(urdun.getString("name"));
            }
            cat_id = Integer.parseInt(get_cat_id);
        } catch (SQLException ex) {
            Logger.getLogger(CategoryAction.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cat_bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        stockName = new javax.swing.JTextField();
        catUpdateBtn = new javax.swing.JButton();
        catDeleteBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        cat_bg.setBackground(new java.awt.Color(0, 51, 204));
        cat_bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cat_bgMouseDragged(evt);
            }
        });
        cat_bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cat_bgMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Категори");

        catUpdateBtn.setText("Засах");
        catUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catUpdateBtnActionPerformed(evt);
            }
        });

        catDeleteBtn.setText("Устгах");
        catDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catDeleteBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Буцах");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cat_bgLayout = new javax.swing.GroupLayout(cat_bg);
        cat_bg.setLayout(cat_bgLayout);
        cat_bgLayout.setHorizontalGroup(
            cat_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cat_bgLayout.createSequentialGroup()
                .addGroup(cat_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cat_bgLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(stockName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cat_bgLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(backBtn)
                        .addGap(29, 29, 29)
                        .addComponent(catDeleteBtn)
                        .addGap(27, 27, 27)
                        .addComponent(catUpdateBtn)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        cat_bgLayout.setVerticalGroup(
            cat_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cat_bgLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(cat_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(stockName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cat_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catUpdateBtn)
                    .addComponent(catDeleteBtn)
                    .addComponent(backBtn))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cat_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cat_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void catUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catUpdateBtnActionPerformed
        getCatName = stockName.getText().toString().trim();
        if (getCatName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Та утгаа оруулна уу.");
        } else {
            try {
                urdun = db.login("select name from categories where name = '" + getCatName + "'");
                if (urdun.next()) {
                    JOptionPane.showMessageDialog(null, getCatName + " Категори жагсаалтанд байна.");
                } else {
                    db.exec("update categories set name = '" + getCatName + "' where id = " + cat_id);
                    setVisible(false);
                    d.Tbl_Cat_Hewleh();
                    d.setVisible(true);
                    d.tabbedPane.setSelectedIndex(3);
                }
            } catch (SQLException ex) {
                Logger.getLogger(CategoryAction.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_catUpdateBtnActionPerformed

    private void catDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catDeleteBtnActionPerformed
        try {
            urdun = db.login("select * from aguulah where cid = " + cat_id);
            if (urdun.next()) {
                JOptionPane.showMessageDialog(null, "Энэ категори-г устгах боломжгүй байна.");
            } else {
                db.exec("delete from categories where id = " + cat_id);
                setVisible(false);
                d.Tbl_Cat_Hewleh();
                d.setVisible(true);
                d.tabbedPane.setSelectedIndex(3);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CategoryAction.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_catDeleteBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        setVisible(false);
        d.tabbedPane.setSelectedIndex(3);
        d.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void cat_bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cat_bgMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_cat_bgMouseDragged

    private void cat_bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cat_bgMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_cat_bgMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton catDeleteBtn;
    private javax.swing.JButton catUpdateBtn;
    private javax.swing.JPanel cat_bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField stockName;
    // End of variables declaration//GEN-END:variables
}
