package admin;

import dbconnector.dbconnect;
import login.LoginProgram;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ariunbuyan
 */
public class Dashboard extends javax.swing.JFrame {

    dbconnect db = new dbconnect();
    Connection con;
    PreparedStatement stmt;
    ResultSet urdun;
    TableModel tm_awsan;
    int xMouse, yMouse;

    String addCatName;

    /* Aguulah */
    String bname, btoo, bprice, birsen_date, bduusah_date;
    String getCatName, tbl_aguulah_utga;
    int cat_id, aguulah_row;

    /* Shop */
    String sname, sadd, tbl_shop_utga;
    int shop_row;

    /* Category */
    String tbl_category_utga;
    int cat_row;

    /* Share Stock */
    String tbl_share_utga;
    int stock_share_row;
    
    /* Huwaarilsan delguuriin baraa */
    String tbl_huwiarilsan_baraa;
    int baraa_share_row;

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setLocation(100, 50);
        shopAddress.setLineWrap(true);

        Tbl_Cat_Hewleh();
        Tbl_Aguulah_Hewleh();
        Tbl_Shop_Hewleh();
        Aguulah_Combo_Category_Name();

        Tbl_Stock_Share();
        Tbl_Shop_huwiarilsan_baraa();
        Combo_Shop_Huwiarlah();
    }

    public void Tbl_Cat_Hewleh() {
        tm_awsan = db.tabled_hewleh("SELECT id as Id, name as 'Category Name' FROM categories ORDER BY Id DESC");
        tbl_category.setModel(tm_awsan);
    }

    public void Tbl_Shop_Hewleh() {
        tm_awsan = db.tabled_hewleh("SELECT id as Id, sname as Name, address as Address FROM shops ORDER BY id DESC");
        tbl_shops.setModel(tm_awsan);
    }

    public void Tbl_Aguulah_Hewleh() {
        tm_awsan = db.tabled_hewleh("SELECT a.id as '№', a.name as 'Барааны нэр', a.too as 'Барааны тоо', a.price as 'Барааны үнэ', "
                + "c.name as 'Төрөл', a.irsen_date as 'Ирсэн өдөр', a.duusah_date as 'Дуусах өдөр'"
                + "FROM aguulah a, categories c WHERE a.cid = c.id ORDER BY a.id DESC");
        tbl_aguulah.setModel(tm_awsan);
    }

    public void Tbl_Stock_Share() {
        tm_awsan = db.tabled_hewleh("SELECT a.id as '№', a.name as 'Барааны нэр', a.too as 'Барааны тоо', a.price as 'Барааны үнэ', "
                + "c.name as 'Төрөл', a.irsen_date as 'Ирсэн өдөр', a.duusah_date as 'Дуусах өдөр'"
                + "FROM aguulah a, categories c WHERE a.cid = c.id");
        tbl_stock_share.setModel(tm_awsan);
    }

    public void Tbl_Shop_huwiarilsan_baraa() {
        tm_awsan = db.tabled_hewleh("SELECT b.id, s.sname, a.name, c.name, a.too, a.price "
                + "FROM baraa b, aguulah a, shops s, categories c "
                + "WHERE b.aid = a.id AND b.sid = s.id AND a.cid = c.id");
        tbl_Shopd_awsan_baraa.setModel(tm_awsan);
    }

    public void Aguulah_Combo_Category_Name() {
        try {
            urdun = db.login("SELECT name FROM categories ORDER BY id DESC");
            while (urdun.next()) {
                aguulah_combo_cat_name.addItem(urdun.getString("name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void Combo_Shop_Huwiarlah() {
        try {
            urdun = db.login("SELECT sname FROM shops ORDER BY id DESC");
            while (urdun.next()) {
                combo_shop_list.addItem(urdun.getString("sname").substring(0, 1).toUpperCase() + urdun.getString("sname").substring(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser = new datechooser.beans.DateChooserDialog();
        bg = new javax.swing.JPanel();
        toolbar = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        tabbedPane = new javax.swing.JTabbedPane();
        aguulah = new javax.swing.JPanel();
        PanelAddStock = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        stockName = new javax.swing.JTextField();
        stockToo = new javax.swing.JTextField();
        stockPrice = new javax.swing.JTextField();
        aguulah_combo_cat_name = new javax.swing.JComboBox<>();
        baraaNemeh = new javax.swing.JButton();
        stockIrsenDate = new com.toedter.calendar.JDateChooser();
        stockDuusahDate = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_aguulah = new javax.swing.JTable();
        delguur = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        shopName = new javax.swing.JTextField();
        shopAddress = new javax.swing.JTextArea();
        DelguurNemeh = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_shops = new javax.swing.JTable();
        huwiarlah = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_stock_share = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_Shopd_awsan_baraa = new javax.swing.JTable();
        combo_shop_list = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        catName = new javax.swing.JTextField();
        CategoryNemeh = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_category = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 540));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toolbar.setBackground(new java.awt.Color(153, 153, 153));
        toolbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                toolbarMouseDragged(evt);
            }
        });
        toolbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                toolbarMousePressed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout toolbarLayout = new javax.swing.GroupLayout(toolbar);
        toolbar.setLayout(toolbarLayout);
        toolbarLayout.setHorizontalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarLayout.createSequentialGroup()
                .addContainerGap(944, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(53, 53, 53))
        );
        toolbarLayout.setVerticalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        tabbedPane.setBackground(new java.awt.Color(0, 51, 153));

        aguulah.setBackground(new java.awt.Color(0, 102, 153));
        aguulah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, new java.awt.Color(0, 0, 153), new java.awt.Color(0, 51, 153)));
        aguulah.setPreferredSize(new java.awt.Dimension(1000, 465));

        PanelAddStock.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));
        PanelAddStock.setPreferredSize(new java.awt.Dimension(400, 275));

        jLabel1.setText("Барааны нэр:");

        jLabel2.setText("Барааны тоо:");

        jLabel3.setText("Барааны үнэ:");

        jLabel4.setText("Категори");

        jLabel5.setText("Ирсэн  он, сар, өдөр");

        jLabel6.setText("Дуусах он, сар, өдөр");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 51));
        jLabel7.setText("Агуулахад бараа нэмэх");

        baraaNemeh.setText("Агуулахад бараа нэмэх");
        baraaNemeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baraaNemehActionPerformed(evt);
            }
        });

        stockIrsenDate.setDateFormatString("yyyy-MM-dd");

        stockDuusahDate.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout PanelAddStockLayout = new javax.swing.GroupLayout(PanelAddStock);
        PanelAddStock.setLayout(PanelAddStockLayout);
        PanelAddStockLayout.setHorizontalGroup(
            PanelAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAddStockLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(PanelAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stockName)
                    .addComponent(stockToo)
                    .addComponent(stockPrice)
                    .addComponent(aguulah_combo_cat_name, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(baraaNemeh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockIrsenDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockDuusahDate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(PanelAddStockLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelAddStockLayout.setVerticalGroup(
            PanelAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAddStockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(29, 29, 29)
                .addGroup(PanelAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAddStockLayout.createSequentialGroup()
                        .addComponent(stockName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stockToo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stockPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aguulah_combo_cat_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(PanelAddStockLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(PanelAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(stockIrsenDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(PanelAddStockLayout.createSequentialGroup()
                        .addComponent(stockDuusahDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(baraaNemeh)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_aguulah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        tbl_aguulah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "№", "Барааны нэр", "Барааны тоо", "Барааны үнэ", "Ирсэн хугацаа", "Дуусах хугацаа"
            }
        ));
        tbl_aguulah.setPreferredSize(new java.awt.Dimension(370, 65));
        tbl_aguulah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_aguulahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_aguulah);
        if (tbl_aguulah.getColumnModel().getColumnCount() > 0) {
            tbl_aguulah.getColumnModel().getColumn(0).setResizable(false);
            tbl_aguulah.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout aguulahLayout = new javax.swing.GroupLayout(aguulah);
        aguulah.setLayout(aguulahLayout);
        aguulahLayout.setHorizontalGroup(
            aguulahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aguulahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelAddStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        aguulahLayout.setVerticalGroup(
            aguulahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aguulahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aguulahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(PanelAddStock, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Агуулах", aguulah);

        delguur.setBackground(new java.awt.Color(0, 102, 153));
        delguur.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, new java.awt.Color(0, 0, 153), new java.awt.Color(0, 51, 153)));
        delguur.setPreferredSize(new java.awt.Dimension(1000, 465));

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        shopName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        shopAddress.setColumns(20);
        shopAddress.setRows(5);
        shopAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        DelguurNemeh.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        DelguurNemeh.setText("Дэлгүүр нэмэх");
        DelguurNemeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelguurNemehActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 51));
        jLabel8.setText("Шинээр дэлгүүр нэмэх хэсэг");

        jLabel9.setText("Дэлгүүрийн нэр:");

        jLabel10.setText("Дэлгүүрийн хаяг:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shopAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shopName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(DelguurNemeh, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(shopName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(shopAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(DelguurNemeh)
                .addGap(55, 55, 55))
        );

        tbl_shops.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_shops.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_shopsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_shops);

        javax.swing.GroupLayout delguurLayout = new javax.swing.GroupLayout(delguur);
        delguur.setLayout(delguurLayout);
        delguurLayout.setHorizontalGroup(
            delguurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, delguurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        delguurLayout.setVerticalGroup(
            delguurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delguurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(delguurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Дэлгүүр", delguur);

        huwiarlah.setBackground(new java.awt.Color(0, 102, 153));
        huwiarlah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, new java.awt.Color(0, 0, 153), new java.awt.Color(0, 51, 153)));
        huwiarlah.setPreferredSize(new java.awt.Dimension(1000, 465));

        tbl_stock_share.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_stock_share.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_stock_shareMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_stock_share);

        tbl_Shopd_awsan_baraa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Shopd_awsan_baraa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_Shopd_awsan_baraaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbl_Shopd_awsan_baraa);

        combo_shop_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));
        combo_shop_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_shop_listActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout huwiarlahLayout = new javax.swing.GroupLayout(huwiarlah);
        huwiarlah.setLayout(huwiarlahLayout);
        huwiarlahLayout.setHorizontalGroup(
            huwiarlahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, huwiarlahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(huwiarlahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_shop_list, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        huwiarlahLayout.setVerticalGroup(
            huwiarlahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(huwiarlahLayout.createSequentialGroup()
                .addGroup(huwiarlahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(huwiarlahLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(huwiarlahLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(combo_shop_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Бараа хувиарлах", huwiarlah);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, new java.awt.Color(0, 0, 153), new java.awt.Color(0, 51, 153)));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 465));

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        CategoryNemeh.setText("Категори нэмэх");
        CategoryNemeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryNemehActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 255, 0));
        jLabel11.setText("Категори нэмэх хэсэг");

        jLabel12.setText("Категори нэр:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(catName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel11))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(CategoryNemeh, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel11)
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(28, 28, 28)
                .addComponent(CategoryNemeh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_category.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_categoryMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_category);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Категори", jPanel2);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane)
                .addContainerGap())
        );

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void baraaNemehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baraaNemehActionPerformed
        bname = stockName.getText().toString().trim();
        btoo = stockToo.getText().toString().trim();
        bprice = stockPrice.getText().toString().trim();

        birsen_date = ((JTextField) stockIrsenDate.getDateEditor().getUiComponent()).getText();
        bduusah_date = ((JTextField) stockDuusahDate.getDateEditor().getUiComponent()).getText();

        getCatName = aguulah_combo_cat_name.getSelectedItem().toString();

        if (bname.isEmpty() || btoo.isEmpty() || bprice.isEmpty() || birsen_date.isEmpty() || bduusah_date.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Алдаа гарлаа.");
        } else {
            try {
                urdun = db.login("select id from categories where name = '" + getCatName + "'");
                if (urdun.next()) {
                    cat_id = urdun.getInt("id");
                }

                db.exec("insert into aguulah (name, too, price, cid, irsen_date, duusah_date)"
                        + "VALUES ('" + bname + "','" + btoo + "','" + bprice + "',"
                        + "'" + cat_id + "','" + birsen_date + "','" + bduusah_date + "')");
                Tbl_Aguulah_Hewleh();
                Aguulah_Combo_Category_Name();
                stockName.setText(null);
                stockToo.setText(null);
                stockPrice.setText(null);
            } catch (SQLException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_baraaNemehActionPerformed

    private void CategoryNemehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryNemehActionPerformed
        addCatName = catName.getText().toString().trim();
        if (addCatName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Категори нэмэх утга хоосон байж болохгүй!");
        } else {
            try {
                urdun = db.login("select name from categories where name = '" + addCatName + "'");
                if (urdun.next()) {
                    JOptionPane.showMessageDialog(null, addCatName + " Категори жагсаалтанд байна.");
                } else {
                    db.exec("insert into categories (name) values ('" + addCatName + "')");
                    Tbl_Cat_Hewleh();
                    Aguulah_Combo_Category_Name();
                    catName.setText(null);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_CategoryNemehActionPerformed

    private void tbl_aguulahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_aguulahMouseClicked
        aguulah_row = tbl_aguulah.getSelectedRow();
        tbl_aguulah_utga = (tbl_aguulah.getModel().getValueAt(aguulah_row, 0)).toString();
        AguulahDesc aguulah = new AguulahDesc(tbl_aguulah_utga);
        aguulah.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_tbl_aguulahMouseClicked

    private void DelguurNemehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelguurNemehActionPerformed
        sname = shopName.getText().toString().trim();
        sadd = shopAddress.getText().toString().trim();

        if (sname.isEmpty() || sadd.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Та хоосон утга оруулах боломжгүй.");
        } else {
            db.exec("insert into shops (sname, address) values ('" + sname + "', '" + sadd + "')");
            Tbl_Shop_Hewleh();
            Combo_Shop_Huwiarlah();
            shopName.setText(null);
            shopAddress.setText(null);
        }
    }//GEN-LAST:event_DelguurNemehActionPerformed

    private void tbl_categoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_categoryMouseClicked
        cat_row = tbl_category.getSelectedRow();
        tbl_category_utga = (tbl_category.getModel().getValueAt(cat_row, 0)).toString();
        CategoryAction cat = new CategoryAction(tbl_category_utga);
        cat.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_tbl_categoryMouseClicked

    private void tbl_shopsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_shopsMouseClicked
        shop_row = tbl_shops.getSelectedRow();
        tbl_shop_utga = (tbl_shops.getModel().getValueAt(shop_row, 0)).toString();
        ShopAction shop = new ShopAction(tbl_shop_utga);
        setVisible(false);
        shop.setVisible(true);
    }//GEN-LAST:event_tbl_shopsMouseClicked

    private void combo_shop_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_shop_listActionPerformed
        String combo_shop_baraa_huwiarilah = combo_shop_list.getSelectedItem().toString();

        try {
            urdun = db.login("select id from shops where sname = '" + combo_shop_baraa_huwiarilah + "'");
            if (urdun.next()) {
                tm_awsan = db.tabled_hewleh("SELECT b.id, s.sname, a.name, c.name, a.too, a.price "
                        + "FROM baraa b, aguulah a, shops s, categories c "
                        + "WHERE b.aid = a.id AND b.sid = s.id AND a.cid = c.id AND s.id = " + urdun.getString("id"));
                tbl_Shopd_awsan_baraa.setModel(tm_awsan);
            } else {
                tm_awsan = db.tabled_hewleh("SELECT b.id, s.sname, a.name, c.name, a.too, a.price "
                        + "FROM baraa b, aguulah a, shops s, categories c "
                        + "WHERE b.aid = a.id AND b.sid = s.id AND a.cid = c.id");
                tbl_Shopd_awsan_baraa.setModel(tm_awsan);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_combo_shop_listActionPerformed

    private void tbl_stock_shareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_stock_shareMouseClicked
        stock_share_row = tbl_stock_share.getSelectedRow();
        tbl_share_utga = (tbl_stock_share.getModel().getValueAt(stock_share_row, 0)).toString();
        BaraaHuwiarlah share = new BaraaHuwiarlah(tbl_share_utga);
        setVisible(false);
        share.setVisible(true);
    }//GEN-LAST:event_tbl_stock_shareMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        LoginProgram login = new LoginProgram();
        setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void toolbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolbarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_toolbarMouseDragged

    private void toolbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolbarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_toolbarMousePressed

    private void tbl_Shopd_awsan_baraaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_Shopd_awsan_baraaMouseClicked
        baraa_share_row = tbl_Shopd_awsan_baraa.getSelectedRow();
        tbl_huwiarilsan_baraa = (tbl_Shopd_awsan_baraa.getModel().getValueAt(baraa_share_row, 0)).toString();
        HuwiarilsanBaraaZasah zasah = new HuwiarilsanBaraaZasah(tbl_huwiarilsan_baraa);
        setVisible(false);
        zasah.setVisible(true);
    }//GEN-LAST:event_tbl_Shopd_awsan_baraaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CategoryNemeh;
    private javax.swing.JButton DelguurNemeh;
    private javax.swing.JPanel PanelAddStock;
    private javax.swing.JPanel aguulah;
    private javax.swing.JComboBox<String> aguulah_combo_cat_name;
    private javax.swing.JButton baraaNemeh;
    private javax.swing.JPanel bg;
    private javax.swing.JTextField catName;
    private javax.swing.JComboBox<String> combo_shop_list;
    private datechooser.beans.DateChooserDialog dateChooser;
    private javax.swing.JPanel delguur;
    private javax.swing.JPanel huwiarlah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel logout;
    private javax.swing.JTextArea shopAddress;
    private javax.swing.JTextField shopName;
    private com.toedter.calendar.JDateChooser stockDuusahDate;
    private com.toedter.calendar.JDateChooser stockIrsenDate;
    private javax.swing.JTextField stockName;
    private javax.swing.JTextField stockPrice;
    private javax.swing.JTextField stockToo;
    public javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tbl_Shopd_awsan_baraa;
    private javax.swing.JTable tbl_aguulah;
    private javax.swing.JTable tbl_category;
    private javax.swing.JTable tbl_shops;
    private javax.swing.JTable tbl_stock_share;
    private javax.swing.JPanel toolbar;
    // End of variables declaration//GEN-END:variables
}
