/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import dbconnector.dbconnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ariunbuyan
 */
public class HuwiarilsanBaraaZasah extends javax.swing.JFrame {

    dbconnect db = new dbconnect();
    Dashboard d = new Dashboard();
    ResultSet urdun;

    String sname, name, btoo, price, cname;
    int baraa_id, shop_id, bid, xMouse, yMouse;

    /* Delete */
    int getOne, delHariu, getTwo;
    int editHariu, hariu;

    /**
     * Creates new form HuwiarilsanBaraaZasah
     */
    public HuwiarilsanBaraaZasah(String get_huwi_id) {
        initComponents();

        try {
            urdun = db.login("SELECT b.id as bid, a.name, b.btoo, a.price, c.name as cname, s.sname, s.id "
                    + "FROM aguulah a, baraa b, categories c, shops s "
                    + "WHERE b.sid = s.id AND b.aid = a.id AND a.cid = c.id AND a.id = " + get_huwi_id);
            if (urdun.next()) {
                sname = urdun.getString("sname");
                name = urdun.getString("name");
                btoo = urdun.getString("btoo");
                price = urdun.getString("price");
                cname = urdun.getString("cname");

                baraa_id = Integer.parseInt(get_huwi_id);
                shop_id = urdun.getInt("id");
                bid = urdun.getInt("bid");
            } else {
                setVisible(false);
                d.tabbedPane.setSelectedIndex(2);
                d.setVisible(true);
            }
        } catch (Exception e) {
        }
        viewSname.setText("Дэлгүүрийн: " + sname);
        viewBname.setText("Барааны нэр: " + name);
        viewBtoo.setText("Барааны тоо: " + btoo);
        viewBprice.setText("Барааны үнэ: " + price);

        viewBcat.setText("Барааны төрөл: " + cname);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        toolbar = new javax.swing.JPanel();
        viewSname = new javax.swing.JLabel();
        viewBname = new javax.swing.JLabel();
        viewBtoo = new javax.swing.JLabel();
        viewBprice = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        viewBcat = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        huwiarilsan_baraa_ustgah = new javax.swing.JButton();
        huwiarilsan_baraa_zasah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toolbar.setBackground(new java.awt.Color(102, 102, 102));
        toolbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                toolbarMouseDragged(evt);
            }
        });
        toolbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                toolbarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout toolbarLayout = new javax.swing.GroupLayout(toolbar);
        toolbar.setLayout(toolbarLayout);
        toolbarLayout.setHorizontalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        toolbarLayout.setVerticalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        viewSname.setText("Дэлгүүрийн нэр");

        viewBname.setText("Барааны нэр");

        viewBtoo.setText("Барааны тоо");

        viewBprice.setText("Барааны үнэ");

        jLabel5.setText("Бараа нэмж авах тоо");

        viewBcat.setText("Барааны төрөл");

        backBtn.setText("Буцах");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        huwiarilsan_baraa_ustgah.setText("Устгах");
        huwiarilsan_baraa_ustgah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huwiarilsan_baraa_ustgahActionPerformed(evt);
            }
        });

        huwiarilsan_baraa_zasah.setText("Засах");
        huwiarilsan_baraa_zasah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huwiarilsan_baraa_zasahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewSname)
                            .addComponent(viewBprice)
                            .addComponent(viewBtoo)
                            .addComponent(viewBname)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewBcat)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(backBtn))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(huwiarilsan_baraa_ustgah)
                                        .addGap(39, 39, 39)
                                        .addComponent(huwiarilsan_baraa_zasah))
                                    .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewSname)
                .addGap(18, 18, 18)
                .addComponent(viewBname)
                .addGap(18, 18, 18)
                .addComponent(viewBtoo)
                .addGap(18, 18, 18)
                .addComponent(viewBprice)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(viewBcat)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(huwiarilsan_baraa_ustgah)
                    .addComponent(huwiarilsan_baraa_zasah))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        setVisible(false);
        d.tabbedPane.setSelectedIndex(2);
        d.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void huwiarilsan_baraa_ustgahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huwiarilsan_baraa_ustgahActionPerformed
        try {
            urdun = db.login("SELECT b.btoo FROM baraa b, aguulah a, shops s "
                    + "WHERE b.sid = s.id AND b.aid = a.id AND b.sid = " + shop_id + " AND b.aid = " + baraa_id);
            if (urdun.next()) {
                getOne = urdun.getInt("btoo");

                urdun = db.login("select too from aguulah where id = " + baraa_id);
                if (urdun.next()) {
                    delHariu = urdun.getInt("too") + getOne;
                    db.exec("update aguulah set too = " + delHariu + " where id = " + baraa_id);
                    db.exec("delete from baraa where id = " + bid);
                    setVisible(false);
                    d.tabbedPane.setSelectedIndex(2);
                    d.Tbl_Shop_huwiarilsan_baraa();
                    d.setVisible(true);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_huwiarilsan_baraa_ustgahActionPerformed

    private void huwiarilsan_baraa_zasahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huwiarilsan_baraa_zasahActionPerformed
        editHariu = Integer.parseInt(number.getText().toString());

        try {
            urdun = db.login("select btoo from baraa where sid = " + shop_id + " and aid = " + baraa_id);
            if (urdun.next()) {
                getOne = urdun.getInt("btoo");

                urdun = db.login("select too from aguulah where id = " + baraa_id);
                if (urdun.next()) {
                    if (editHariu <= urdun.getInt("too")) {
                        hariu = getOne + editHariu;
                        db.exec("update baraa set btoo = " + hariu + " where id = " + bid);
                        delHariu = urdun.getInt("too") - editHariu;
                        db.exec("update aguulah set too = " + delHariu + " where id = " + baraa_id);
                        setVisible(false);
                        d.Tbl_Shop_huwiarilsan_baraa();
                        d.Tbl_Aguulah_Hewleh();
                        d.Tbl_Stock_Share();
                        d.tabbedPane.setSelectedIndex(2);
                        d.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Таны оруулсан барааны тоо хүрэхгүй байна.");
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(HuwiarilsanBaraaZasah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_huwiarilsan_baraa_zasahActionPerformed

    private void toolbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolbarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_toolbarMouseDragged

    private void toolbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolbarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_toolbarMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton huwiarilsan_baraa_ustgah;
    private javax.swing.JButton huwiarilsan_baraa_zasah;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField number;
    private javax.swing.JPanel toolbar;
    private javax.swing.JLabel viewBcat;
    private javax.swing.JLabel viewBname;
    private javax.swing.JLabel viewBprice;
    private javax.swing.JLabel viewBtoo;
    private javax.swing.JLabel viewSname;
    // End of variables declaration//GEN-END:variables
}
